Employee Management/Task1/Controllers/EmployeeAddressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Task1.Models;

namespace Task1.Controllers
{
    public class EmployeeAddressesController : Controller
    {
        private Model1 db = new Model1();

        // GET: EmployeeAddresses
        public async Task<ActionResult> Index(int? id)
        {
            var employeeAddresses = db.EmployeeAddresses.Include(e => e.city1).Include(e => e.country1).Include(e => e.Employee).Include(e => e.state1);
            if (id != null && id > 0)
                employeeAddresses.Where(e => e.eid == id);
            return View(await employeeAddresses.ToListAsync());
        }

        // GET: EmployeeAddresses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeAddress employeeAddress = await db.EmployeeAddresses.FindAsync(id);
            if (employeeAddress == null)
            {
                return HttpNotFound();
            }
            return View(employeeAddress);
        }

        // GET: EmployeeAddresses/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeAddress employeeAddress = new EmployeeAddress();
            ViewBag.country = new SelectList(db.countries, "id", "name");
            employeeAddress.eid = Convert.ToInt32(id);
            return View(employeeAddress);
        }

        // POST: EmployeeAddresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EmployeeAddress employeeAddress)
        {
            if (ModelState.IsValid)
            {
                employeeAddress.status = 1;
                db.EmployeeAddresses.Add(employeeAddress);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.country = new SelectList(db.countries, "id", "name", employeeAddress.country);
            return View(employeeAddress);
        }

        // GET: EmployeeAddresses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeAddress employeeAddress = await db.EmployeeAddresses.FindAsync(id);
            if (employeeAddress == null)
            {
                return HttpNotFound();
            }
            BindDropDown(employeeAddress);
            return View(employeeAddress);
        }

        private void BindDropDown(EmployeeAddress employeeAddress)
        {
            ViewBag.country = new SelectList(db.countries.Where(e => e.status == 1).OrderBy(o => o.name), "id", "name", employeeAddress.country);
            ViewBag.state = new SelectList(db.states.Where(e => e.status == 1).OrderBy(o => o.name), "id", "name", employeeAddress.state);
            ViewBag.city = new SelectList(db.cities.Where(e => e.status == 1).OrderBy(o => o.name), "id", "name", employeeAddress.city);
        }
        // POST: EmployeeAddresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EmployeeAddress employeeAddress)
        {
            if (ModelState.IsValid)
            {
                EmployeeAddress empadd = await db.EmployeeAddresses.FindAsync(employeeAddress.id);
                if (empadd != null)
                {

                    empadd.addressline1 = employeeAddress.addressline1;
                    empadd.addressline2 = employeeAddress.addressline2;
                    empadd.landmark = employeeAddress.landmark;
                    empadd.country = employeeAddress.country;
                    empadd.state = employeeAddress.state;
                    empadd.city = employeeAddress.city;
                    empadd.pin = employeeAddress.pin;
                    empadd.contact = employeeAddress.contact;
                    empadd.ispermanant = employeeAddress.ispermanant;
                    empadd.status = employeeAddress.status;
                    db.Entry(empadd).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            BindDropDown(employeeAddress);
            return View(employeeAddress);
        }

        // GET: EmployeeAddresses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeAddress employeeAddress = await db.EmployeeAddresses.FindAsync(id);
            if (employeeAddress == null)
            {
                return HttpNotFound();
            }
            return View(employeeAddress);
        }

        // POST: EmployeeAddresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            EmployeeAddress employeeAddress = await db.EmployeeAddresses.FindAsync(id);
            db.EmployeeAddresses.Remove(employeeAddress);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Employee Management/Task1/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Task1.Models;

namespace Task1.Controllers
{
    public class EmployeesController : Controller
    {
        private Model1 db = new Model1();

        // GET: Employees
        public async Task<ActionResult> Index()
        {
            return View(await db.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Employee employee)
        {   
            if (ModelState.IsValid)
            {
                int eCount = db.Employees.Count() + 1;
                employee.eno = "E" + (0000 + eCount).ToString();
                employee.estatus = 1;
                db.Employees.Add(employee);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                Employee emp = await db.Employees.FindAsync(employee.eid);
                if(emp!=null)
                {
                    emp.ename = employee.ename;
                    emp.edept = employee.edept;
                    emp.econtact = employee.econtact;
                    emp.eemail = employee.eemail;
                    emp.estatus = employee.estatus;
                    db.Entry(emp).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = await db.Employees.FindAsync(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Employee employee = await db.Employees.FindAsync(id);
            db.Employees.Remove(employee);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Employee Management/Task1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TASK 1</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TASK 1", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Employee Addresses", "Index", "EmployeeAddresses")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Task</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        window.onbeforeunload = function () {
            $("input[type=button], input[type=submit]").attr("disabled", "disabled");

        };
        function bindDropDown(url, controlid, postData, value) {
            $.ajax({
                cache: false,
                type: "POST",
                url: url,
                data: postData,
                dataType: "json",
                traditional: true,
                success: function (data) {
                    var ddl = $("#" + controlid + "");
                    ddl.html('');
                    ddl.append($('<option></option>').val(0).html("--Select--"));
                    $.each(data, function (id, option) {
                        ddl.append($('<option></option>').val(option.Value).html(option.Text));
                    });
                    if (value != null && value != "")
                        $("#" + controlid + "").val(value);
                    else $("#" + controlid + "").val(0);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    console.log(ajaxOptions + 'Failed to retrieve states.');
                }
            });
        }

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>